import "./globals.css";
import type { Metadata, Route } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/components/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="flex justify-center gap-4">
						<ActiveLink activeClassName="underline" href="/" title="Home">
							Home
						</ActiveLink>
						<ActiveLink
							activeClassName="underline"
							href={"/products" as Route}
							title="All"
							exact={false}
						>
							Produkty
						</ActiveLink>
					</ul>
				</nav>
				<main className="container-xl flex min-h-screen flex-col items-center justify-between p-24">
					{children}
				</main>
			</body>
		</html>
	);
}
